---
upstream:
  url: http://127.0.0.1:9000/
#  exec: ./sleep.sh 60
server:
  addr: ":8080"
  readTimeout: 10
  writeTimeout: 10
  idleTimeout: 20
  maxHeaderBytes: 4096
http_header_out:
  set:
    X-XSS_Protection: "1; mode=block"
    X-Content-Type-Options: "nosniff"
    X-Permitted-Cross-Domain-Policies: "none"
    Content-Security-Policy: "default-src 'self'; child-src 'none'"
  del:
    - Server
  only:
    - Server
    - Date
    - Content-Length
    - Content-Type
http_header_in:
  set:
    User-Agent: httpsanitizer/0.1
  del:
    - X-Origin-Host
  only:
    - Host
    - Accept
    - User-Agent
    - Content-Length
    - Content-Type
    - X-Forwarded-Host
    - X-Origin-Host
form_params:
  text:
    type: text
    maxlen: 10
    strip_html: true
    strip_chars: "'`/"
    strip_quotation: true
    strip_binary: true
  num:
    type: numeric
    maxval: 4294967296
  email:
    type: email
    maxlen: 200
    strip_chars: "'`/"
  ip:
    type: ip
  url:
    type: url
    maxlen: 200
    strip_chars: "'`"
    strip_binary: true
  path:
    type: path
    maxlen: 100
    strip_chars: "'`"
    strip_binary: true
  filename:
    type: filename
    maxlen: 50
    strip_chars: "'`"
    strip_binary: true
  time:
    type: unixtime
  